"""artifacts and action items

Revision ID: 0953420f1a6a
Revises: 286db52aad07
Create Date: 2026-08-23 01:40:11.163243
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0953420f1a6a'
down_revision: Union[str, None] = '286db52aad07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_agent_id', sa.UUID(), nullable=True),
    sa.Column('owner_agent_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('due', sa.String(length=64), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='meetings'
    )
    op.create_index(op.f('ix_meetings_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False, schema='meetings')
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='meetings'
    )
    op.create_index(op.f('ix_meetings_artifacts_meeting_id'), 'artifacts', ['meeting_id'], unique=False, schema='meetings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_artifacts_meeting_id'), table_name='artifacts', schema='meetings')
    op.drop_table('artifacts', schema='meetings')
    op.drop_index(op.f('ix_meetings_action_items_meeting_id'), table_name='action_items', schema='meetings')
    op.drop_table('action_items', schema='meetings')
    # ### end Alembic commands ###
